"""Add target company fields to projects table

Revision ID: 865e7f1afd29
Revises: f06175b09853
Create Date: 2025-12-16 20:06:13.436991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '865e7f1afd29'
down_revision: Union[str, Sequence[str], None] = 'f06175b09853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_popups_dates', table_name='popups')
    op.drop_index('idx_popups_is_active', table_name='popups')
    op.drop_table('popups')
    op.alter_column('broadcast_messages', 'sender_id',
               existing_type=sa.UUID(),
               comment='Admin ID who sent the broadcast',
               existing_nullable=False)
    op.alter_column('message_threads', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='general, support, performance',
               existing_nullable=False,
               existing_server_default=sa.text("'general'::character varying"))
    op.alter_column('message_threads', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='open, resolved, closed',
               existing_nullable=False,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('message_threads', 'created_by',
               existing_type=sa.UUID(),
               comment='User ID who created the thread',
               existing_nullable=False)
    op.alter_column('message_threads', 'assigned_to',
               existing_type=sa.UUID(),
               comment='Admin ID assigned to handle this thread',
               existing_nullable=True)
    op.add_column('projects', sa.Column('target_company_name', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('target_business_number', sa.String(length=12), nullable=True))
    op.drop_column('projects', 'target_audience')
    op.alter_column('thread_messages', 'sender_id',
               existing_type=sa.UUID(),
               comment='User ID who sent the message',
               existing_nullable=False)
    op.alter_column('thread_messages', 'sender_type',
               existing_type=sa.VARCHAR(length=20),
               comment='admin or member',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('thread_messages', 'sender_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='admin or member',
               existing_nullable=False)
    op.alter_column('thread_messages', 'sender_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User ID who sent the message',
               existing_nullable=False)
    op.add_column('projects', sa.Column('target_audience', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('projects', 'target_business_number')
    op.drop_column('projects', 'target_company_name')
    op.alter_column('message_threads', 'assigned_to',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Admin ID assigned to handle this thread',
               existing_nullable=True)
    op.alter_column('message_threads', 'created_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User ID who created the thread',
               existing_nullable=False)
    op.alter_column('message_threads', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='open, resolved, closed',
               existing_nullable=False,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('message_threads', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='general, support, performance',
               existing_nullable=False,
               existing_server_default=sa.text("'general'::character varying"))
    op.alter_column('broadcast_messages', 'sender_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Admin ID who sent the broadcast',
               existing_nullable=False)
    op.create_table('popups',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('link_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('width', sa.INTEGER(), server_default=sa.text('600'), autoincrement=False, nullable=False),
    sa.Column('height', sa.INTEGER(), server_default=sa.text('400'), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=20), server_default=sa.text("'center'::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.VARCHAR(length=10), server_default=sa.text("'false'::character varying"), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='popups_pkey')
    )
    op.create_index('idx_popups_is_active', 'popups', ['is_active', 'created_at'], unique=False)
    op.create_index('idx_popups_dates', 'popups', ['start_date', 'end_date'], unique=False)
    # ### end Alembic commands ###
